import type { Metadata } from 'next';
import { Crimson_Pro, Roboto } from 'next/font/google';
import './globals.css';

const crimson = Crimson_Pro({
  subsets: ['latin'],
  variable: '--font-crimson',
  weight: ['200', '400', '500', '700'],
});
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-roboto',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${crimson.variable} ${roboto.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
